# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/968fe75f-6a74-4df3-85dc-3f942ae232cd";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/23E6-682B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/data/media" =
    { device = "/dev/disk/by-uuid/911845c3-f772-412a-9344-1713d9200aaf";
      fsType = "ext4";
      options = [ "nofail" ];
    };

  fileSystems."/data/redtopia" =
    { device = "//192.168.8.1/music/redtopia";
      fsType = "cifs";
      options = [ "nofail" "uid=988" "gid=988" "dir_mode=0775" "file_mode=0775" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b518f24f-9a12-478c-9e48-e0ebf742583f"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth-wg-br.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth54c4548.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethf3317b3.useDHCP = lib.mkDefault true;
  # networking.interfaces.wg-br.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
