# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "uas" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/968fe75f-6a74-4df3-85dc-3f942ae232cd";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/23E6-682B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/data/media" =
    { device = "/dev/disk/by-uuid/911845c3-f772-412a-9344-1713d9200aaf";
      fsType = "ext4";
      options = [ "nofail" ];
    };

  fileSystems."/data/media/library/music" =
    { device = "/dev/disk/by-uuid/930fd766-4b07-4122-bfbc-1ff85fc2f35b";
      fsType = "ext4";
      options = [ "nofail" ];
    };

  fileSystems."/data/redtopia" =
    { device = "//192.168.8.1/music/redtopia";
      fsType = "cifs";
      options = [ "nofail" "uid=988" "gid=988" "dir_mode=0775" "file_mode=0775" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b518f24f-9a12-478c-9e48-e0ebf742583f"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
